"use client";

import { FormEvent, useEffect, useState } from "react";

type Provider = { id: string; type: "github" | "logto" | "oidc"; name: string; slug: string; client_id: string; issuer?: string; authorization_url: string; token_url: string; user_info_url: string; scopes: string; enabled: number };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error || "请求失败"); return data; }

export default function AdminPage() {
  const [authenticated, setAuthenticated] = useState<boolean | undefined>(undefined); const [providers, setProviders] = useState<Provider[]>([]); const [type, setType] = useState<Provider["type"]>("github"); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  async function loadProviders() { setProviders((await api<{ providers: Provider[] }>("/api/admin/oauth")).providers); }
  useEffect(() => { api<{ authenticated: boolean }>("/api/admin/session").then(async ({ authenticated }) => { setAuthenticated(authenticated); if (authenticated) await loadProviders(); }).catch(() => setAuthenticated(false)); }, []);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setNotice(""); const form = new FormData(event.currentTarget); try { await api("/api/admin/session", { method: "POST", body: JSON.stringify({ token: form.get("token") }) }); setAuthenticated(true); await loadProviders(); } catch (error) { setNotice(error instanceof Error ? error.message : "验证失败"); } finally { setBusy(false); } }
  async function createProvider(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setNotice(""); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); try { await api("/api/admin/oauth", { method: "POST", body: JSON.stringify({ ...payload, type, enabled: true }) }); event.currentTarget.reset(); setNotice("OAuth 配置已添加"); await loadProviders(); } catch (error) { setNotice(error instanceof Error ? error.message : "保存失败"); } finally { setBusy(false); } }
  async function remove(id: string) { if (!confirm("确定删除这个 OAuth 配置吗？相关用户绑定也会被移除。")) return; setBusy(true); try { await api("/api/admin/oauth", { method: "DELETE", body: JSON.stringify({ id }) }); await loadProviders(); setNotice("OAuth 配置已删除"); } catch (error) { setNotice(error instanceof Error ? error.message : "删除失败"); } finally { setBusy(false); } }
  if (authenticated === undefined) return <main className="standalone-shell"><section className="standalone-card">正在验证管理会话…</section></main>;
  if (!authenticated) return <main className="standalone-shell admin-token-shell"><section className="standalone-card admin-token-card"><p className="eyebrow">ADMIN ACCESS</p><h1>验证 Admin Token</h1><p>Token 仅用于建立 8 小时的安全管理会话，不会保存到浏览器脚本或数据库。</p><form onSubmit={login}><label>Admin Token<input name="token" type="password" autoComplete="current-password" required autoFocus /></label><button className="primary-button wide" disabled={busy}>{busy ? "正在验证…" : "进入管理页面"}</button></form>{notice && <p className="form-notice">{notice}</p>}</section></main>;
  const defaults = type === "github" ? { name: "GitHub", scopes: "read:user user:email" } : type === "logto" ? { name: "Logto", scopes: "openid profile email" } : { name: "OIDC", scopes: "openid profile email" };
  return <main className="standalone-shell"><header className="standalone-header"><a className="brand" href="/"><span className="brand-mark">N</span>NotiCenter Admin</a><button onClick={async () => { await api("/api/admin/session", { method: "DELETE" }); setAuthenticated(false); }}>退出管理</button></header><section className="admin-console"><div className="standalone-card"><p className="eyebrow">OAUTH PROVIDERS</p><h1>OAuth 配置</h1><div className="social-list">{providers.map((provider) => <article className="social-row" key={provider.id}><span className={`oauth-logo ${provider.type}`}>{provider.type === "github" ? "GH" : provider.type === "logto" ? "L" : "ID"}</span><div><strong>{provider.name}</strong><small>{provider.client_id} · /{provider.slug}</small></div><button disabled={busy} onClick={() => remove(provider.id)}>删除</button></article>)}</div>{providers.length === 0 && <div className="empty-state"><strong>还没有 OAuth 配置</strong></div>}</div><div className="standalone-card"><p className="eyebrow">NEW PROVIDER</p><h1>添加配置</h1><form className="oauth-config-form" onSubmit={createProvider}><label>类型<select value={type} onChange={(event) => setType(event.target.value as Provider["type"])}><option value="github">GitHub</option><option value="logto">Logto</option><option value="oidc">通用 OIDC</option></select></label><div className="form-grid"><label>显示名称<input name="name" key={`${type}-name`} defaultValue={defaults.name} required /></label><label>标识 slug<input name="slug" placeholder="例如 github" /></label></div><div className="form-grid"><label>Client ID<input name="clientId" required /></label><label>Client Secret<input name="clientSecret" type="password" required /></label></div>{type !== "github" && <label>Issuer URL<input name="issuer" type="url" required={type === "logto"} placeholder="https://tenant.logto.app/oidc" /></label>}{type === "oidc" && <><label>Authorization URL<input name="authorizationUrl" type="url" required /></label><label>Token URL<input name="tokenUrl" type="url" required /></label><label>UserInfo URL<input name="userInfoUrl" type="url" required /></label></>}<label>Scopes<input name="scopes" key={`${type}-scopes`} defaultValue={defaults.scopes} required /></label><button className="primary-button wide" disabled={busy}>{busy ? "正在保存…" : "保存 OAuth 配置"}</button></form>{notice && <p className="form-notice">{notice}</p>}<p className="callback-help">回调地址格式：<code>{typeof window === "undefined" ? "https://your-domain" : window.location.origin}/api/oauth/配置-slug/callback</code></p></div></section></main>;
}
