import { requireAdminToken } from "../../../../lib/server/admin-auth";
import { errorResponse, json } from "../../../../lib/server/auth";
import { id, runtime } from "../../../../lib/server/crypto";

const values = (input: Record<string, unknown>) => ({
  name: String(input.name ?? "").trim().slice(0, 60), description: String(input.description ?? "").trim().slice(0, 300),
  priceCents: Math.max(0, Math.round(Number(input.priceCents) || 0)), currency: String(input.currency || "CNY").trim().toUpperCase().slice(0, 8),
  durationDays: Math.max(1, Math.min(3650, Math.round(Number(input.durationDays) || 30))), deviceLimit: Math.max(1, Math.min(10000, Math.round(Number(input.deviceLimit) || 3))),
  enabled: input.enabled === false ? 0 : 1, sortOrder: Math.max(-10000, Math.min(10000, Math.round(Number(input.sortOrder) || 0))),
});

export async function GET(request: Request) { try { await requireAdminToken(request); const result = await runtime.DB.prepare(`SELECT p.*, (SELECT count(*) FROM activation_codes ac WHERE ac.plan_id = p.id) AS code_count, (SELECT count(*) FROM user_plan_subscriptions s WHERE s.plan_id = p.id AND s.status = 'active' AND s.expires_at > unixepoch()) AS subscriber_count FROM plans p ORDER BY sort_order ASC, created_at DESC`).all(); return json({ plans: result.results }); } catch (error) { return errorResponse(error); } }
export async function POST(request: Request) { try { await requireAdminToken(request); const input = await request.json() as Record<string, unknown>; const v = values(input); if (!v.name) return json({ error: "请输入套餐名称" }, 400); const planId = id("plan"); await runtime.DB.prepare("INSERT INTO plans (id, name, description, price_cents, currency, duration_days, device_limit, enabled, sort_order, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, unixepoch(), unixepoch())").bind(planId, v.name, v.description, v.priceCents, v.currency, v.durationDays, v.deviceLimit, v.enabled, v.sortOrder).run(); return json({ ok: true, id: planId }, 201); } catch (error) { return errorResponse(error); } }
export async function PATCH(request: Request) { try { await requireAdminToken(request); const input = await request.json() as Record<string, unknown> & { id?: string }; const v = values(input); if (!input.id || !v.name) return json({ error: "套餐信息不完整" }, 400); const result = await runtime.DB.prepare("UPDATE plans SET name = ?, description = ?, price_cents = ?, currency = ?, duration_days = ?, device_limit = ?, enabled = ?, sort_order = ?, updated_at = unixepoch() WHERE id = ?").bind(v.name, v.description, v.priceCents, v.currency, v.durationDays, v.deviceLimit, v.enabled, v.sortOrder, input.id).run(); if (!result.meta.changes) return json({ error: "套餐不存在" }, 404); return json({ ok: true }); } catch (error) { return errorResponse(error); } }
export async function DELETE(request: Request) { try { await requireAdminToken(request); const input = await request.json() as { id?: string }; const result = await runtime.DB.prepare("UPDATE plans SET enabled = 0, updated_at = unixepoch() WHERE id = ?").bind(input.id).run(); if (!result.meta.changes) return json({ error: "套餐不存在" }, 404); return json({ ok: true }); } catch (error) { return errorResponse(error); } }
