import { BARK_MESSAGE_FIELDS, type AdapterConfig, type DeliveryResult, type PushAdapter, type PushMessage, type PushProvider } from "./types";
async function result(response: Response): Promise<DeliveryResult> { return { ok: response.ok, status: response.status, retryable: response.status === 429 || response.status >= 500, detail: response.ok ? undefined : (await response.text()).slice(0, 300) }; }
function safeHttpUrl(raw: string) { const url = new URL(raw.trim()); if (!["https:", "http:"].includes(url.protocol)) throw new Error("仅支持 HTTP(S) 地址"); return url; }
function standardPayload(message: PushMessage) { return { ...(message.payload ?? {}), title: message.title, body: message.body, ...(message.url === undefined ? {} : { url: message.url }), ...(message.group === undefined ? {} : { group: message.group }) }; }
export const barkAdapter: PushAdapter = { provider: "bark", normalizeEndpoint(raw) { const url = safeHttpUrl(raw); const key = url.pathname.split("/").filter(Boolean)[0]; if (!key || /^(your[-_]?key|key|device[-_]?key|这里|你的密钥)$/i.test(decodeURIComponent(key))) throw new Error("Bark 地址中没有有效的设备 Key"); url.pathname = `/${key}`; url.hash = ""; url.search = ""; return url.toString().replace(/\/$/, ""); }, async send(endpoint, message) { const payload = standardPayload(message); delete payload.device_key; delete payload.device_keys; return result(await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json; charset=utf-8" }, body: JSON.stringify(payload) })); } };
function mappedPayload(message: PushMessage, config?: AdapterConfig) { const sourcePayload = standardPayload(message); const map = Object.fromEntries(BARK_MESSAGE_FIELDS.map((field) => [field, field])); Object.assign(map, config?.mapping); const payload: Record<string, unknown> = {}; for (const source of BARK_MESSAGE_FIELDS) { const target = map[source]?.trim(); const value = sourcePayload[source]; if (target && value !== undefined) payload[target] = value; } return payload; }
export const ntfyAdapter: PushAdapter = { provider: "ntfy", normalizeEndpoint(raw) { return safeHttpUrl(raw).toString().replace(/\/$/, ""); }, async send(endpoint, message, config) { const mapping = config?.mapping ?? { title: "title", body: "message", url: "click", group: "tags" }; return result(await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json; charset=utf-8" }, body: JSON.stringify(mappedPayload(message, { mapping })) })); } };
export const webhookAdapter: PushAdapter = { provider: "webhook", normalizeEndpoint(raw) { return safeHttpUrl(raw).toString(); }, async send(endpoint, message, config) { return result(await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json; charset=utf-8", "user-agent": "NotiCenter/1.0" }, body: JSON.stringify(mappedPayload(message, config)) })); } };
const adapters: Record<PushProvider, PushAdapter> = { bark: barkAdapter, ntfy: ntfyAdapter, webhook: webhookAdapter };
export function getPushAdapter(provider: PushProvider) { return adapters[provider]; }
