"use client";

import { FormEvent, useEffect, useState } from "react";

type User = { id: string; displayName: string };
type Provider = { id: string; type: string; name: string; slug: string; identity_id?: string; username?: string; email?: string };
type Plan = { id: string; name: string; description: string; price_cents: number; currency: string; duration_days: number; device_limit: number };
type Entitlement = { planId: string | null; planName: string; deviceLimit: number; expiresAt: number | null; source: string };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error || "请求失败"); return data; }
const price = (plan: Plan) => plan.price_cents === 0 ? "免费" : new Intl.NumberFormat("zh-CN", { style: "currency", currency: plan.currency || "CNY" }).format(plan.price_cents / 100);

export default function ProfilePage() {
  const [user, setUser] = useState<User | null>(); const [providers, setProviders] = useState<Provider[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [entitlement, setEntitlement] = useState<Entitlement>(); const [endpointCount, setEndpointCount] = useState(0); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const me = await api<{ user: User | null }>("/api/me"); setUser(me.user); if (!me.user) return; const [social, planData] = await Promise.all([api<{ providers: Provider[] }>("/api/oauth/providers"), api<{ plans: Plan[]; entitlement: Entitlement; endpointCount: number }>("/api/plans")]); setProviders(social.providers); setPlans(planData.plans); setEntitlement(planData.entitlement); setEndpointCount(planData.endpointCount); }
  useEffect(() => { const params = new URLSearchParams(location.search); if (params.get("message")) setNotice(params.get("message")!); load().catch((error) => setNotice(error instanceof Error ? error.message : "加载失败")); }, []);
  async function run(task: () => Promise<unknown>, success: string) { setBusy(true); setNotice(""); try { await task(); setNotice(success); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "操作失败"); } finally { setBusy(false); } }
  async function disconnect(identityId: string) { if (confirm("确定解除这个社交账户的绑定吗？")) await run(() => api("/api/oauth/providers", { method: "DELETE", body: JSON.stringify({ identityId }) }), "已解除社交账户绑定"); }
  async function subscribe(plan: Plan) { if (plan.price_cents > 0) { setNotice("付费套餐请在下方输入对应激活码完成订阅"); document.getElementById("activation-code")?.focus(); return; } await run(() => api("/api/plans", { method: "POST", body: JSON.stringify({ planId: plan.id }) }), "免费套餐订阅成功"); }
  async function redeem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await run(async () => { await api("/api/plans/redeem", { method: "POST", body: JSON.stringify({ code: form.get("code") }) }); event.currentTarget.reset(); }, "激活码兑换成功，套餐权益已经生效"); }
  if (user === undefined) return <main className="standalone-shell"><section className="standalone-card">正在加载个人中心…</section></main>;
  if (!user) return <main className="standalone-shell"><section className="standalone-card"><p className="eyebrow">PROFILE</p><h1>请先登录</h1><p>使用通知地址登录后即可管理套餐和社交账户。</p><a className="primary-button standalone-action" href="/">返回并登录</a></section></main>;
  return <main className="standalone-shell profile-wide"><header className="standalone-header"><a className="brand" href="/"><span className="brand-mark">N</span>NotiCenter</a><a href="/">返回主题中心</a></header>{notice && <p className="form-notice profile-notice">{notice}</p>}<section className="profile-grid"><div className="profile-main"><section className="standalone-card profile-card"><p className="eyebrow">CURRENT PLAN</p><h1>{entitlement?.planName || "普通用户"}</h1><div className="entitlement-stats"><div><strong>{endpointCount} / {entitlement?.deviceLimit || 3}</strong><small>已用设备</small></div><div><strong>{entitlement?.expiresAt ? new Date(entitlement.expiresAt * 1000).toLocaleDateString("zh-CN") : "长期有效"}</strong><small>套餐到期</small></div></div><p>账号 ID：<code>{user.id}</code></p></section><section className="standalone-card profile-card"><p className="eyebrow">AVAILABLE PLANS</p><h1>选择套餐</h1><div className="public-plan-grid">{plans.map((plan) => <article className={entitlement?.planId === plan.id ? "current" : ""} key={plan.id}><span>{plan.device_limit} 台设备</span><h2>{plan.name}</h2><strong>{price(plan)}</strong><p>{plan.description || `${plan.duration_days} 天有效期`}</p><small>{plan.duration_days} 天</small><button disabled={busy || entitlement?.planId === plan.id} onClick={() => subscribe(plan)}>{entitlement?.planId === plan.id ? "当前套餐" : plan.price_cents === 0 ? "立即订阅" : "使用激活码"}</button></article>)}</div>{plans.length === 0 && <div className="empty-state"><strong>暂无可订阅套餐</strong></div>}</section></div><aside className="profile-side"><section className="standalone-card profile-card"><p className="eyebrow">REDEEM</p><h1>兑换套餐</h1><p>输入管理员提供的激活码，兑换后套餐立即生效。</p><form className="redeem-form" onSubmit={redeem}><input id="activation-code" name="code" placeholder="NTC-XXXX-XXXX-XXXX" autoComplete="off" required /><button className="primary-button" disabled={busy}>兑换</button></form></section><section className="standalone-card profile-card"><p className="eyebrow">SOCIAL ACCOUNTS</p><h1>社交账户</h1><div className="social-list">{providers.map((provider) => <article className="social-row" key={provider.id}><span className={`oauth-logo ${provider.type}`}>{provider.type === "github" ? "GH" : provider.type === "logto" ? "L" : "ID"}</span><div><strong>{provider.name}</strong><small>{provider.identity_id ? provider.username || provider.email || "已连接" : "尚未绑定"}</small></div>{provider.identity_id ? <button disabled={busy} onClick={() => disconnect(provider.identity_id!)}>解绑</button> : <a className="social-connect" href={`/api/oauth/${provider.slug}/start`}>连接</a>}</article>)}</div>{providers.length === 0 && <p className="muted-copy">管理员尚未配置 OAuth 登录。</p>}</section></aside></section></main>;
}
